apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: image-builder
rules:
- apiGroups: ["build.openshift.io"]
  resources: ["*"]
  verbs: ["*"]
  resourceNames: [""]  # Allow access to all secrets
- apiGroups: ["image.openshift.io"]
  resources: ["*"]
  verbs: ["*"]
  resourceNames: [""]  # Allow access to all secrets