apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: custom-pytorch-build 
  namespace: default
spec:
  source:
    type: Git
    git:
      uri: https://github.com/tnscorcoran/rhoai-custom-image.git
    contextDir: helm
  strategy:
    type: Docker                      
    dockerStrategy:
      dockerfilePath: Containerfile
      from:
        kind: ImageStreamTag  
        name: cuda-notebook-custom:latest
  output:
    to:
      kind: ImageStreamTag
      name: custom-pytorch-build:latest
  triggers:
  - type: ImageChange